# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 389)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 529, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuOr_amento = QtWidgets.QMenu(self.menubar)
        self.menuOr_amento.setObjectName("menuOr_amento")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionFixos = QtWidgets.QAction(MainWindow)
        self.actionFixos.setObjectName("actionFixos")
        self.menuArquivo.addAction(self.actionSair)
        self.menuOr_amento.addAction(self.actionFixos)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuOr_amento.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TemperCalc - Software Para Calculos de Vidros Temperados"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuOr_amento.setTitle(_translate("MainWindow", "Orçamento"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionFixos.setText(_translate("MainWindow", "Vidros Fixos"))

