# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(529, 389)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 529, 21))
        self.menubar.setObjectName("menubar")
        self.menuArquivo = QtWidgets.QMenu(self.menubar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuOrcamento = QtWidgets.QMenu(self.menubar)
        self.menuOrcamento.setObjectName("menuOrcamento")
        self.menuCadastro = QtWidgets.QMenu(self.menubar)
        self.menuCadastro.setObjectName("menuCadastro")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionCadastro_de_vidros = QtWidgets.QAction(MainWindow)
        self.actionCadastro_de_vidros.setObjectName("actionCadastro_de_vidros")
        self.actionCadastro_de_Aluminios = QtWidgets.QAction(MainWindow)
        self.actionCadastro_de_Aluminios.setObjectName("actionCadastro_de_Aluminios")
        self.actionCadastro_de_Acessorios = QtWidgets.QAction(MainWindow)
        self.actionCadastro_de_Acessorios.setObjectName("actionCadastro_de_Acessorios")
        self.actionVidros_Fixos = QtWidgets.QAction(MainWindow)
        self.actionVidros_Fixos.setObjectName("actionVidros_Fixos")
        self.menuArquivo.addAction(self.actionSair)
        self.menuOrcamento.addAction(self.actionVidros_Fixos)
        self.menuCadastro.addAction(self.actionCadastro_de_vidros)
        self.menuCadastro.addAction(self.actionCadastro_de_Aluminios)
        self.menuCadastro.addAction(self.actionCadastro_de_Acessorios)
        self.menubar.addAction(self.menuArquivo.menuAction())
        self.menubar.addAction(self.menuOrcamento.menuAction())
        self.menubar.addAction(self.menuCadastro.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TemperCalc - Software Para Calculos de Vidros Temperados"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuOrcamento.setTitle(_translate("MainWindow", "Orçamento"))
        self.menuCadastro.setTitle(_translate("MainWindow", "Cadastro"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
        self.actionCadastro_de_vidros.setText(_translate("MainWindow", "Cadastro de Vidros"))
        self.actionCadastro_de_Aluminios.setText(_translate("MainWindow", "Cadastro de Alumínios"))
        self.actionCadastro_de_Acessorios.setText(_translate("MainWindow", "Cadastro de Acessórios"))
        self.actionVidros_Fixos.setText(_translate("MainWindow", "Vidros Fixos"))
